### ISSUE TITLE
Alternative method for local TWA development

### ISSUE THREAD

**Issue by slavafomin** [Telegram-Web-Apps/twa.js#33]
You've [explained some methods](https://telegram-web-apps.github.io/twa/docs/tutorials-and-recipes/creating-web-app#ngrok) of local development in the documentation.

I want to share another one:

1. Run:

```shell
mkcert -install
```

This will install a root `mkcert` certificate so that your browser won't complain.

2. Run:

```shell
mkdir -p dev/certs && cd dev/certs
mkcert acme.local
```

This will generate self-signed TLS certificate under the `dev/certs` directory.

3. Add the following to your Webpack Dev Server config:

```js
devServer: {
  https: {
    cert: path.resolve(__dirname, 'dev/certs/acme.local.pem'),
    key: path.resolve(__dirname, 'dev/certs/acme.local-key.pem'),
  },
  allowedHosts: [
    'acme.local',
  ],
  port: 8080,
  proxy: {
    '/api/*': {
      target: 'http://localhost:8081',
      secure: false,
      logLevel: 'debug',
      changeOrigin: true,
    },
  },
  // …
},
```

The `https` configuration will use the specified TLS certificates to support HTTPS.

The `proxy` configuration will allow you to redirect traffic to your backend server via HTTPS, so you won't have to configure TLS there as well.

4. Just add `acme.local` to the `hosts` file.

You will be able to open your TWA via `https://acme.local:8080` right inside the Telegram without any issues.

Cheers!

**Comment by heyqbnk** [comment]
Thank you for participation! Have to check everything and will probably share it in docs <3
