### ISSUE TITLE
Error: Unable to get unit "webApp" as long as SDK is not initialized.

### ISSUE THREAD

**Issue by Amurmurmur** [Telegram-Web-Apps/twa.js#77]
**Describe the bug**
Just copy pasted what was in the docs to setup a minimul Webapp

When I call this:
in my App
const webApp = useWebApp();

  useEffect(() => {
    webApp.ready();
  }, [webApp]);

**To Reproduce**
Follow the guide here: https://docs.twa.dev/docs/libraries/twa-js-sdk-react

**Expected behavior**

My main.tsx:
```
import React from "react";
import ReactDOM from "react-dom/client";

import "./index.css";
import { App } from "./app";



ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
      <App />
  </React.StrictMode>
);

```

my app.tsx
```
const options: InitOptions = {
    acceptScrollbarStyle: true,
    checkCompat: true,
    debug: true
  };
const AppWrapped = withSDK(Root);

export function App() {
  return (
    <SDKProvider initOptions={options}>
      <AppWrapped />
    </SDKProvider>
  );
}

```

my root.tsx
```

/**
 * This component is the layer controlling the application display. It displays
 * application in case, the SDK is initialized, displays an error if something
 * went wrong, and a loader if the SDK is warming up.
 */
function Loader({children}: PropsWithChildren<{}>) {
    const {didInit, components, error} = useSDK();
  
    // There were no calls of SDK's init function. It means, we did not
    // even try to do it.
    if (!didInit) {
      return <div>SDK init function is not yet called.</div>;
    }
  
    // Error occurred during SDK init.
    if (error !== null) {
      return <div>Something went wrong.</div>;
    }
  
    // If components is null, it means, SDK is not ready at the
    // moment and currently initializing. Usually, it takes like
    // several milliseconds or something like that, but we should
    // have this check.
    if (components === null) {
      return <div>Warming up SDK.</div>;
    }
  
    // Safely render application.
    return <>{children}</>;
  }

export function Root({ sdk }) {

  return (
    <Loader>
        <div>TEST app</div>
    </Loader>
  )
}

```

Loader gets stuck at Warming up SDK.
When console logging the sdk:
{components: null, didInit: true, error: null}

**Comment by heyqbnk** [comment]
1. What Telegram application are you testing this code in?
2. Have you tried this code in different Telegram applications?

**Comment by heyqbnk** [comment]
Please, try opening your app in the different Telegram application. I assume, problem is specific to the Telegram app for macOS only. It is probably a bug in the platform, not in the package, but it seems like I know the solution

**Comment by heyqbnk** [comment]
As I found out with some other external developer, problem occurs due to the incorrect behaviour of the Telegram app for macOS. The reason is the native application is not responding to `web_app_request_viewport` method, but it [must](https://core.telegram.org/api/web-events#web-app-request-viewport). 

The other important note here, that I could not reproduce this problem using the same native application version. I will release the solution today and will notify you about that.

**Comment by heyqbnk** [comment]
[@twa.js/sdk](https://www.npmjs.com/package/@twa.js/sdk) and [@twa.js/sdk-react](https://www.npmjs.com/package/@twa.js/sdk-react) were updated. Try using the latest versions and let me know if my solution doesn't solve the problem
